artifact_location: /Users/ericwindsor/Documents/EPITA_ERIC/Data_Scicence_Production/mlflow_hands_on-master/mlruns/0
creation_time: 1710928700281
experiment_id: '0'
last_update_time: 1710928700281
lifecycle_stage: active
name: Default
