artifact_uri: /Users/ericwindsor/Documents/EPITA_ERIC/Data_Scicence_Production/mlflow_hands_on-master/mlruns/750660966991525839/2c23a2656a6e457abb06b4d3d520b7cb/artifacts
end_time: 1711310612185
entry_point_name: ''
experiment_id: '750660966991525839'
lifecycle_stage: active
run_id: 2c23a2656a6e457abb06b4d3d520b7cb
run_name: run_test
run_uuid: 2c23a2656a6e457abb06b4d3d520b7cb
source_name: ''
source_type: 4
source_version: ''
start_time: 1711310603341
status: 3
tags: []
user_id: ericwindsor
