artifact_uri: /Users/ericwindsor/Documents/EPITA_ERIC/Data_Scicence_Production/mlflow_hands_on-master/mlruns/750660966991525839/be261d17c6884be4b30b6e8417e31feb/artifacts
end_time: 1711135890880
entry_point_name: ''
experiment_id: '750660966991525839'
lifecycle_stage: active
run_id: be261d17c6884be4b30b6e8417e31feb
run_name: run_test
run_uuid: be261d17c6884be4b30b6e8417e31feb
source_name: ''
source_type: 4
source_version: ''
start_time: 1711135884783
status: 4
tags: []
user_id: ericwindsor
