artifact_location: /Users/ericwindsor/Documents/EPITA_ERIC/Data_Scicence_Production/mlflow_hands_on-master/mlruns/750660966991525839
creation_time: 1710928709234
experiment_id: '750660966991525839'
last_update_time: 1710928709234
lifecycle_stage: active
name: Churn Prediction
