artifact_uri: /Users/ericwindsor/Documents/EPITA_ERIC/Data_Scicence_Production/mlflow_hands_on-master/mlruns/750660966991525839/b701dd962ee94c9e83cec548b5cecd49/artifacts
end_time: 1711310396541
entry_point_name: ''
experiment_id: '750660966991525839'
lifecycle_stage: active
run_id: b701dd962ee94c9e83cec548b5cecd49
run_name: run_test
run_uuid: b701dd962ee94c9e83cec548b5cecd49
source_name: ''
source_type: 4
source_version: ''
start_time: 1711310389729
status: 4
tags: []
user_id: ericwindsor
