artifact_uri: /Users/ericwindsor/Documents/EPITA_ERIC/Data_Scicence_Production/mlflow_hands_on-master/mlruns/750660966991525839/07df599edadb4f4989d0a8c7333852ff/artifacts
end_time: 1711137406272
entry_point_name: ''
experiment_id: '750660966991525839'
lifecycle_stage: active
run_id: 07df599edadb4f4989d0a8c7333852ff
run_name: run_test
run_uuid: 07df599edadb4f4989d0a8c7333852ff
source_name: ''
source_type: 4
source_version: ''
start_time: 1711137398832
status: 3
tags: []
user_id: ericwindsor
