artifact_uri: /Users/ericwindsor/Documents/EPITA_ERIC/Data_Scicence_Production/mlflow_hands_on-master/mlruns/750660966991525839/4a3280c571db4735a4febc845fca7cde/artifacts
end_time: 1711310487058
entry_point_name: ''
experiment_id: '750660966991525839'
lifecycle_stage: active
run_id: 4a3280c571db4735a4febc845fca7cde
run_name: run_test
run_uuid: 4a3280c571db4735a4febc845fca7cde
source_name: ''
source_type: 4
source_version: ''
start_time: 1711310479965
status: 4
tags: []
user_id: ericwindsor
