artifact_uri: /Users/ericwindsor/Documents/EPITA_ERIC/Data_Scicence_Production/mlflow_hands_on-master/mlruns/750660966991525839/b956ac37dbdb456cb9046d351bc4e66c/artifacts
end_time: 1711135953508
entry_point_name: ''
experiment_id: '750660966991525839'
lifecycle_stage: active
run_id: b956ac37dbdb456cb9046d351bc4e66c
run_name: run_test
run_uuid: b956ac37dbdb456cb9046d351bc4e66c
source_name: ''
source_type: 4
source_version: ''
start_time: 1711135944771
status: 3
tags: []
user_id: ericwindsor
